---

- name: install | Copy kubelet binary from download dir
  command: rsync -piu "{{ local_release_dir }}/hyperkube" "{{ bin_dir }}/kubelet"
  changed_when: false
  when: hyperkube_enabled
  tags:
    - hyperkube
    - upgrade

- name: install | Set kubelet binary permissions
  file:
    path: "{{ bin_dir }}/kubelet"
    mode: "0755"
    state: file
  when: hyperkube_enabled
  tags:
    - hyperkube
    - upgrade
  notify: restart kubelet

- name: install | Copy socat wrapper for Container Linux
  command: "{{ docker_bin_dir }}/docker run --rm -v {{ bin_dir }}:/opt/bin {{ install_socat_image_repo }}:{{ install_socat_image_tag }}"
  args:
    creates: "{{ bin_dir }}/socat"
  when: ansible_os_family in ['CoreOS', 'Container Linux by CoreOS']
